)){const holder=document.createElement('div');holder.id='debtChainUi';holder.innerHTML=`
      <div id="editEventModal" class="modal"><div class="sheet"><div class="grab"></div><div class="row between"><h2 id="editEventTitle">Редактировать долговую операцию</h2><button class="btn ghost small" data-debt-close>Закрыть</button></div><div id="editLockedNotice" class="notice hidden"></div><div id="editDebtFields" class="card stack" style="margin-top:12px">
        <label class="field" id="editActionField">Тип действия<select id="editAction"><option value="borrow">Я беру в долг</option><option value="repay">Я возвращаю долг</option><option value="lend">Я даю в долг</option><option value="receive">Мне возвращают долг</option></select></label>
        <label class="field hidden" id="editDirectionField">Направление<select id="editDirection"><option value="owedByMe">Я должен</option><option value="owedToMe">Должны мне</option></select></label>
        <label class="field">Контрагент<select id="editParty"></select></label>
        <label class="field">Сумма<input id="editAmount" type="number" min="0.01" max="999999.99" step="0.01" inputmode="decimal"></label>
        <label class="field">Дата<input id="editDate" type="date"></label>
        <label class="field">Комментарий<textarea id="editDescription" rows="3" maxlength="240" placeholder="Необязательно"></textarea></label>
        <div class="row wrap"><button id="saveEventEdit" class="btn primary">Сохранить и пересчитать</button><button class="btn ghost" data-debt-close>Отмена</button></div>
      </div></div></div>
      <div id="closeChainModal" class="modal"><div class="sheet"><div class="grab"></div><h2>Закрыть долг с <span id="closeChainParty"></span>?</h2><div id="closeChainText" class="notice"></div><div class="row wrap" style="margin-top:12px"><button id="confirmCloseChain" class="btn primary">Закрыть долг</button><button id="continueChain" class="btn ghost">Продолжить цепочку</button></div></div></div>
      <div id="chainDetailsModal" class="modal"><div class="sheet"><div class="grab"></div><div class="row between"><h2 id="chainDetailsTitle">Долговая цепочка</h2><button class="btn ghost small" data-chain-details-close>Закрыть</button></div><div id="chainDetailsStatus" class="notice"></div><div id="chainDetailsEvents" class="chain-movements" style="margin-top:12px"></div><button id="closeFromDetails" class="btn primary block hidden" style="margin-top:12px">Закрыть этот долг</button></div></div>`;document.body.appendChild(holder);}}
function openEditor(eventId){const event=state.events.find(item=>String(item.id)===String(eventId));if(!event)return;const chain=chainById(event.chainId);if(!chain||chain.status==='closed')return openChainDetails(chain?.id);if(!sourceEvent(event))return event.relatedEventId?openEditor(event.relatedEventId):null;editingSourceId=event.id;$('editParty').innerHTML=state.parties.map(party=>`<option value="${party.id}">${esc(party.name)}</option>`).join('');$('editParty').value=event.partyId;$('editAmount').value=round(event.principal);$('editDate').value=event.date||localToday();$('editDescription').value=event.description||'';const isAction=event.kind==='action';$('editActionField').classList.toggle('hidden',!isAction);$('editDirectionField').classList.toggle('hidden',isAction);if(isAction)$('editAction').value=event.action;else $('editDirection').value=event.direction||'owedByMe';$('editEventTitle').textContent='Редактировать долговую операцию';$('editLockedNotice').classList.add('hidden');$('editDebtFields').classList.remove('hidden');$('editEventModal').classList.add('open');}
function saveEditor(){const event=state.events.find(item=>String(item.id)===String(editingSourceId));if(!event)return;const oldChain=chainById(event.chainId);if(!oldChain||oldChain.status==='closed')return toast('Закрытую долговую цепочку изменить нельзя');const amount=round($('editAmount').value),partyId=Number($('editParty').value),date=$('editDate').value||localToday();if(!(amount>0&&amount<=MAX))return toast('Введите сумму от 0,01 до 999 999,99 €');if(!dateAllowedForParty(partyId,date))return toast(`Дата раньше закрытого долга с этим контрагентом`);const previousPartyId=event.partyId;event.principal=amount;event.partyId=partyId;event.date=date;event.description=$('editDescription').value.trim();if(event.kind==='action')event.action=$('editAction').value;else event.direction=$('editDirection').value;if(previousPartyId!==partyId){event.chainId=activeChainForParty(partyId,true).id}
recalculateAll();render();$('editEventModal').classList.remove('open');editingSourceId=n