ёт внутри долговой цепочки'},source,0.01);}
if(source.kind==='action'&&['repay','receive'].includes(source.action)){const expected=source.action==='repay'?(before<0?Math.abs(before):0):(before>0?before:0);const applied=round(Math.min(round(source.principal),round(expected)));const excess=round(round(source.principal)-applied);source.appliedPrincipal=applied;source.overpayment=excess;if(excess>0){const direction=after>0?'owedToMe':'owedByMe';const automatic=`Автоматически создан из переплаты ${money(excess)} при операции «${actionMeta(source.action).verb}» ${formatDate(source.date)}. Введено: ${money(source.principal)}; зачтено в погашение: ${money(applied)}.`;const counter=createDerived({kind:'counterDebt',direction,principal:excess,date:source.date,description:automatic,autoOverpayment:true},source,0.02);source.relatedEventId=counter.id;}}
balance=after;});chain.balance=round(balance);chain.startedDate=sources.length?sources[0].date:(chain.startedDate||localToday());chain.lastDate=sources.length?sources.at(-1).date:(chain.lastDate||chain.startedDate);const party=partyById(chain.partyId);if(party){if(chain.balance>0)party.owedToMe=round(party.owedToMe+chain.balance);else if(chain.balance<0)party.owedByMe=round(party.owedByMe+Math.abs(chain.balance));}});state.debtChains.filter(chain=>chain.status==='closed').forEach(chain=>chain.balance=0);cleanupEmptyChains();save();}
function cleanupEmptyChains(){const empty=state.debtChains.filter(chain=>chain.status==='active'&&sourceEventsForChain(chain.id).length===0);if(!empty.length)return;const ids=new Set(empty.map(chain=>String(chain.id)));state.events=state.events.filter(event=>!ids.has(String(event.chainId)));state.debtChains=state.debtChains.filter(chain=>!ids.has(String(chain.id)));}
function chainCanClose(chain){return Boolean(chain&&chain.status==='active'&&sourceEventsForChain(chain.id).length&&Math.abs(round(chain.balance))<EPS);}
function closeChain(chainIdValue){recalculateAll();const chain=chainById(chainIdValue);if(!chainCanClose(chain))return toast('Закрыть можно только цепочку с нулевым балансом');const sources=sourceEventsForChain(chain.id).sort(eventDateSort);const date=sources.at(-1)?.date||localToday();const party=partyById(chain.partyId);chain.status='closed';chain.closedAt=Date.now();chain.closedDate=date;chain.balance=0;const closure=recordEvent({kind:'chainClosed',partyId:chain.partyId,chainId:chain.id,principal:0,date,description:'Долг закрыт. Цепочка зафиксирована и доступна только для просмотра.',locked:true,createdAt:Date.now()});chain.closeEventId=closure.id;if(party){party.owedByMe=0;party.owedToMe=0}
pendingCloseChainId=null;save();closeAll();render();toast(`Долг с ${party?.name||'контрагентом'} закрыт`);}
function maybeOfferClosure(chainIdValue){const chain=chainById(chainIdValue);if(!chainCanClose(chain))return;const party=partyById(chain.partyId);pendingCloseChainId=chain.id;$('closeChainParty').textContent=party?.name||'Контрагент';$('closeChainText').innerHTML='Баланс этой долговой цепочки стал <strong>0,00 €</strong>.<br><br>После закрытия долг будет считаться полностью погашенным. Все движения останутся в истории, но редактировать их больше будет нельзя.<br><br>Если продолжить цепочку, будущие операции с этим контрагентом будут добавляться сюда же.';$('closeChainModal').classList.add('open');}
function chainStatusText(chain){if(chain.status==='closed')return'Долг закрыт';if(Math.abs(round(chain.balance))<EPS)return'Баланс 0 · цепочка активна';return chain.balance>0?`Мне должны ${money(chain.balance)}`:`Я должен ${money(Math.abs(chain.balance))}`;}
function chainStatusClass(chain){if(chain.status==='closed'||Math.abs(round(chain.balance))<EPS)return'chain-neutral';return chain.balance>0?'flow-good':'flow-bad';}
renderPartyList=function(){ensureChainState();const list=$('partyList');const chains=[...state.debtChains].sort((a,b)=>{if(a.status!==b.status)return a.status==='active'?-1:1;return(b.closedAt||b.createdAt||0)-(a.closedAt||a.createdAt||0);});if(!chains.length){list.innerHTML='<div class="notice">Долговых цепочек пока нет.</div>';return}
list.innerHTML=chains.map(chain=>{const party=partyById(chain.partyId);const number=chainNumber(chain);const period=chain.status==='closed'?`${formatDate(chain.startedDate)} — ${formatDate(chain.closedDate)}`:`с ${formatDate(chain.startedDate)}`;const closeButton=chainCanClose(chain)?`<button class="btn primary small" data-close-chain="${chain.id}">Закрыть долг</button>`:'';ret