(function(){const MAX=999999.99;const EPS=0.0001;let editingSourceId=null;let pendingCloseChainId=null;function round(value){return Math.round((Number(value)||0)*100)/100}
function chainId(){return'chain-'+String(createId()).replace('.','-')}
function sourceEvent(event){return event&&(event.kind==='opening'||event.kind==='action'||(event.kind==='counterDebt'&&!event.derived&&!event.autoOverpayment));}
function debtDelta(event){const amount=round(event.principal??event.amount);if(event.kind==='opening'||event.kind==='counterDebt')return event.direction==='owedToMe'?amount:-amount;if(event.kind==='action')return({borrow:-amount,repay:amount,lend:amount,receive:-amount}[event.action]||0);return 0;}
function chainById(id){return state.debtChains.find(chain=>String(chain.id)===String(id))||null}
function sourceEventsForChain(id){return state.events.filter(event=>String(event.chainId)===String(id)&&sourceEvent(event));}
function allEventsForChain(id){return state.events.filter(event=>String(event.chainId)===String(id));}
function activeChainForParty(partyId,createIfMissing=true){let chain=state.debtChains.find(item=>item.partyId===Number(partyId)&&item.status==='active');if(!chain&&createIfMissing){chain={id:chainId(),partyId:Number(partyId),status:'active',createdAt:Date.now(),startedDate:localToday(),balance:0};state.debtChains.push(chain);}
return chain||null;}
function latestClosedDate(partyId){return state.debtChains.filter(chain=>chain.partyId===Number(partyId)&&chain.status==='closed'&&chain.closedDate).map(chain=>chain.closedDate).sort().at(-1)||'';}
function dateAllowedForParty(partyId,date){const boundary=latestClosedDate(partyId);return!boundary||String(date)>=String(boundary);}
function chainNumber(chain){const list=state.debtChains.filter(item=>item.partyId===chain.partyId).sort((a,b)=>(a.createdAt||0)-(b.createdAt||0));return list.findIndex(item=>String(item.id)===String(chain.id))+1;}
function eventDateSort(a,b){return String(a.date||'').localeCompare(String(b.date||''))||(a.createdAt||0)-(b.createdAt||0);}
function ensureChainState(){state.debtChains=Array.isArray(state.debtChains)?state.debtChains:[];state.debtChains=state.debtChains.filter(chain=>chain&&chain.id&&chain.partyId!==undefined);state.debtChains.forEach(chain=>{chain.partyId=Number(chain.partyId);chain.status=chain.status==='closed'?'closed':'active';chain.createdAt=Number(chain.createdAt)||Date.now();chain.balance=round(chain.balance);});state.parties.forEach(party=>{const active=state.debtChains.filter(chain=>chain.partyId===party.id&&chain.status==='active').sort((a,b)=>(a.createdAt||0)-(b.createdAt||0));if(active.length>1){const keeper=active[0];active.slice(1).forEach(extra=>{state.events.forEach(event=>{if(String(event.chainId)===String(extra.id))event.chainId=keeper.id});state.debtChains=state.debtChains.filter(chain=>String(chain.id)!==String(extra.id));});}});state.parties.forEach(party=>{const unassigned=state.events.filter(event=>event.partyId===party.id&&sourceEvent(event)&&!event.chainId);if(unassigned.length){const chain=activeChainForParty(party.id,true);const first=[...unassigned].sort(eventDateSort)[0];chain.createdAt=Math.min(chain.createdAt||Date.now(),first.createdAt||Date.now());unassigned.forEach(event=>event.chainId=chain.id);}});state.events.forEach(event=>{if(event.chainId)return;const related=state.events.find(candidate=>String(candidate.id)===String(event.relatedEventId));if(related?.chainId){event.chainId=related.chainId;return}
const active=activeChainForParty(event.partyId,false);if(active)event.chainId=active.id;});}
function removeActiveDerived(){const activeIds=new Set(state.debtChains.filter(chain=>chain.status==='active').map(chain=>String(chain.id)));state.events=state.events.filter(event=>{if(!activeIds.has(String(event.chainId)))return true;if(event.kind==='offset')return false;if(event.kind==='counterDebt'&&(event.derived||event.autoOverpayment))return false;return true;});}
function createDerived(data,source,offset){return recordEvent({...data,chainId:source.chainId,partyId:source.partyId,relatedEventId:source.id,derived:true,createdAt:(source.createdAt||Date.now())+offset});}
function recalculateAll(){ensureChainState();removeActiveDerived();state.parties.forEach(party=>{party.owedByMe=0;party.owedToMe=0});state.debtChains.filter(chain=>chain.status==='active').forEach(chain=>{const sources=sourceEventsForChain(chain.id).sort(eventDateSort);let balance=0;sources.forEach(source=>{source.partyId=chain.partyId;if(source.kind==='action'){delete source.relatedEventId;source.appliedPrincipal=round(source.principal);source.overpayment=0;}
const before=round(balance);const delta=round(debtDelta(source));const after=round(before+delta);if(before&&delta&&Math.sign(before)!==Math.sign(delta)){const offsetAmount=round(Math.min(Math.abs(before),Math.abs(delta)));if(offsetAmount>0)createDerived({kind:'offset',principal:offsetAmount,date:source.date,description:'Автоматический взаимозач