ull;const candidates=[oldChain,activeChainForParty(partyId,false)].filter(Boolean);const zero=candidates.find(chain=>chainCanClose(chain));if(zero)maybeOfferClosure(zero.id);else toast('Операция изменена, долговые цепочки пересчитаны');}
function saveDebtActionWithChain(){const party=selectedParty(),amount=round($('principal').value),date=$('date').value||localToday();if(!party)return toast('Выберите или создайте контрагента');if(!(amount>0&&amount<=MAX))return toast('Введите сумму от 0,01 до 999 999,99 €');if(!dateAllowedForParty(party.id,date))return toast('Дата относится к уже закрытой долговой цепочке');const chain=activeChainForParty(party.id,true);const source=recordEvent({kind:'action',action:state.action,partyId:party.id,chainId:chain.id,principal:amount,date,description:$('description').value.trim()});if(['repay','receive'].includes(state.action))state.test.repayment=true;state.lastDate=date;recalculateAll();$('principal').value='';$('description').value='';render();if(chainCanClose(chain))maybeOfferClosure(chain.id);else{if(round(source.overpayment)>0)toast('Переплата автоматически стала встречным долгом');else toast('Долговое действие сохранено');}}
function saveOpeningWithChain(){const party=partyById($('openingParty').value),amount=round($('openingAmount').value),date=$('date').value||localToday();if(!party)return toast('Выберите контрагента');if(!(amount>0&&amount<=MAX))return toast('Введите сумму от 0,01 до 999 999,99 €');if(!dateAllowedForParty(party.id,date))return toast('Дата относится к уже закрытой долговой цепочке');const chain=activeChainForParty(party.id,true);recordEvent({kind:'opening',partyId:party.id,chainId:chain.id,direction:$('openingDirection').value,principal:amount,date,description:$('openingComment').value.trim()||'Исторический стартовый остаток'});state.test.opening=true;state.selectedPartyId=party.id;recalculateAll();closeAll();render();if(chainCanClose(chain))maybeOfferClosure(chain.id);else toast('Стартовый долг добавлен');}
function installStyles(){if($('debtChainStyles'))return;const style=document.createElement('style');style.id='debtChainStyles';style.textContent='.chain-card{border:1px solid var(--line);border-radius:16px;padding:13px;background:#fff;display:grid;gap:10px}.chain-card.closed{background:#f5f7f6}.chain-state{font-size:12px;font-weight:800;border-radius:999px;padding:6px 9px;background:var(--soft)}.chain-neutral{color:var(--muted)}.chain-actions{margin-top:2px}.chain-movements{display:grid;gap:8px}.chain-movement{display:grid;grid-template-columns:minmax(0,1fr) auto;gap:12px;align-items:center;border:1px solid var(--line);border-radius:14px;background:#fff;padding:12px}.history-item.editable{cursor:pointer}.history-item.editable:active,.chain-card:active{transform:scale(.995)}#editEventModal input,#editEventModal select,#editEventModal textarea{font-size:16px}';document.head.appendChild(style);}
function normalizeSections(){const section=$('partyList')?.closest('section');if(section){const title=section.querySelector('h2');if(title)title.textContent='Долги';const tiny=section.querySelector('.tiny');if(tiny)tiny.textContent='Все активные и закрытые долговые цепочки по всем контрагентам.';}
const historyTitle=$('history')?.closest('section')?.querySelector('h2');if(historyTitle)historyTitle.textContent='История долговых операций';}
function replaceInteractionNodes(){const history=$('history');if(history&&!history.dataset.chainListeners){const fresh=history.cloneNode(false);fresh.dataset.chainListeners='true';history.replaceWith(fresh);fresh.addEventListener('click',event=>{const edit=event.target.closest('[data-edit-debt-event]');if(edit)return openEditor(edit.dataset.editDebtEvent);const view=event.target.closest('[data-view-chain]');if(view)return openChainDetails(view.dataset.viewChain);});fresh.addEventListener('keydown',event=>{if(event.key!=='Enter'&&event.key!==' ')return;const edit=event.target.closest('[data-edit-debt-event]');const view=event.target.closest('[data-view-chain]');if(edit||view){event.preventDefault();edit?openEditor(edit.dataset.editDebtEvent):openChainDetails(view.dataset.viewChain)}});}
const partyList=$('partyList');partyList.onclick=event=>{const close=event.target.closest('[data-close-chain]');if(close){event.stopPropagation();return maybeOfferClosure(close.dataset.closeChain)}
const view=event.target.closest('[data-view-chain]');if(view){event.stopPropagation();return openChainDetails(view.dataset.viewChain)}
const card=event.target.closest('[data-party]');if(!card)return;state.selectedPartyId=Number(card.dataset.party);$('part